---
title: "plotLm"
author: "Jameson Quinn and Kyle Mahowald"
date: "April 19, 2015"
output:
  ioslides_presentation:
    incremental: true
---

```{r, include=F}
source('plotLm.R')
library(rmarkdown)
```
## Standard lm diagnotic plots

Say we have some 80 data points that we with to model using $y \sim X1 + X2 + X3$. Here are the resulting diagnostic plots:

```{r, results='asis', fig.height=5, fig.width=5, warning=F, message=F, echo=F}
set.seed(43)
n = 80
x <- data.frame(rmvnorm(n, c(0, 0, 1), .6 * (diag(3) + matrix(.3, 3, 3))))
x$X4 <- c(rep(1, n/2), rep(0, n/2))
y <- x$X1 + 2*x$X2 + 1.2*x$X3^2 + rnorm(n,0,.2) + rnorm(n, x$X4, 1)
x$X4 <- as.factor(x$X4)
l <- lm(y ~ X1 + X2 + X3 + X4 , data=x)
par(mfrow = c(2,2))
plot(l)
par(mfrow = c(1,1))
```

## Can we do better?

```{r, results='asis', fig.height=6, fig.width=7, warning=F, message=F, echo=F}
gginc(1,by1var.seq(l, adjustedData=stages(NULL,F), connection=stages(NULL,F), rawData=stages(list(),F), line=stages(NULL,F), loess=stages(NULL,F),rug=stages(list(alpha=0),F)))

```

## Can we do better (2)?

```{r, results='asis', fig.height=6, fig.width=7, warning=F, message=F, echo=F}
gginc(1:2,by1var(l, "X3", adjustedData=stages(NULL,F), connection=stages(NULL,F), rawData=stages(list(),F), line=stages(NULL,F), loess=stages(NULL,F),rug=stages(list(alpha=0),F)))

```


```{r, fig.height=10, fig.width=10, warning=F, message=F, echo=F}
#d <- read.csv('rts.csv')
#d$AgeSubjectNum <- as.numeric(d$AgeSubject)
#d$RTlexdec.e = exp(d$RTlexdec)
#d$LengthInLetters <- scale(d$LengthInLetters)[, 1]
#l <- lm(RTnaming ~ AgeSubject + WrittenFrequency + LengthInLetters + Familiarity, data=d)
#by1var.seq(l, thin=.2, breakupby='AgeSubject')
#by1var.seq(l, thin=.2, breakupby='LengthInLetters')

```


